name: GitHub Profile Summary Cards

on:
  schedule:
    - cron: "0 0 * * *"  # 毎日UTC 0時に実行
  workflow_dispatch:  # 手動実行も可能

permissions:
  contents: write

jobs:
  summary-cards:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: ${{ github.repository_owner }}
